@startuml

'abstract class AbstractList
'abstract AbstractCollection
'interface List
'interface Collection
'
'List <|-- AbstractList
'Collection <|-- AbstractCollection
'
'Collection <|- List
'AbstractCollection <|- AbstractList
'AbstractList <|-- ArrayList
'
'class ArrayList {
'Object[] elementData
'size()
'}
'
'enum TimeUnit {
'DAYS
'HOURS
'MINUTES
'}
interface NewsGetter{
    + String getNewsXml();
    + String getNewsItem();
    + String getCorruptedItem()
    + String getCorruptedNewsXml();
    + String getPartlyCorruptedNews();
    + String getNewsCount();
}
Abstract class NewsGetterStub{
    # String newsXml;
    # String newItemXml;
}

NewsGetterStub --|>NewsGetter
GazetaNewsGetter  --|> NewsGetterStub
LentaNewsGetter  --|> NewsGetterStub


@enduml