@startuml

class NewsCollector
class RssNewsRecycleViewAdapter
class RssNewsRecycleView
class RssNewsFragment

NewsCollector --* RssNewsRecycleViewAdapter
RssNewsFragment *- RssNewsRecycleViewAdapter
RssNewsFragment *-- RssNewsRecycleView
RssNewsRecycleView -- RssNewsRecycleViewAdapter

@enduml